disabled_rules:
- trailing_whitespace
- vertical_whitespace
- identifier_name

opt_in_rules: # some rules are only opt-in
- empty_count
- force_unwrapping

whitelist_rules:
excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
- Source/ExcludedFolder
- Source/ExcludedFile.swift

# configurable rules can be customized from this configuration file
# binary rules can set their severity level

force_cast: error # implicitly
force_unwrapping: error # implicitly
force_try:
severity: error # explicitly

line_length:
warning: 120
error: 150
ignores_function_declarations: true
ignores_comments: true
ignores_urls: true

function_body_length:
warning: 300
error: 500

function_parameter_count:
warning: 6
error: 8

type_body_length:
warning: 300
error: 500

file_length:
warning: 1000
error: 1500
ignore_comment_only_lines: true

cyclomatic_complexity:
warning: 15
error: 25

reporter: "xcode"
